"""initial schema

Revision ID: f3c22344783c
Revises: 
Create Date: 2026-05-30 07:44:34.649489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f3c22344783c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('media_group_id', sa.String(length=64), nullable=True),
    sa.Column('meal_type', sa.String(length=32), nullable=True),
    sa.Column('hunger', sa.Integer(), nullable=True),
    sa.Column('satiety', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meals_media_group_id'), ['media_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meals_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meals_user_id'), ['user_id'], unique=False)

    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('shoulders_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hips_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurements_measured_at'), ['measured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_user_id'), ['user_id'], unique=False)

    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_user_goal')
    )
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_goals_user_id'), ['user_id'], unique=False)

    op.create_table('meal_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=False),
    sa.Column('file_unique_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_photos_meal_id'), ['meal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_photos_meal_id'))

    op.drop_table('meal_photos')
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_goals_user_id'))

    op.drop_table('user_goals')
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurements_user_id'))
        batch_op.drop_index(batch_op.f('ix_measurements_measured_at'))

    op.drop_table('measurements')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meals_user_id'))
        batch_op.drop_index(batch_op.f('ix_meals_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_meals_media_group_id'))

    op.drop_table('meals')
    op.drop_table('users')
    # ### end Alembic commands ###
